[0m23:59:47.273862 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 23:59:47.619902 | a8d7da62-dbfa-4818-8989-00da8424161e ==============================
[0m23:59:47.619902 [info ] [MainThread]: Running with dbt=1.10.2
[0m23:59:47.649841 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/atef/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:59:47.659418 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/atef/project/E-Commerce-Order-Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:59:47.689325 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 1.2211412, "process_in_blocks": "0", "process_kernel_time": 5.595554, "process_mem_max_rss": "90008", "process_out_blocks": "8", "process_user_time": 11.611856}
[0m23:59:47.703882 [debug] [MainThread]: Command `dbt run` failed at 23:59:47.703288 after 1.24 seconds
[0m23:59:47.708118 [debug] [MainThread]: Flushing usage events
[0m02:16:39.014226 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 02:16:39.132231 | d8701647-326c-4c4b-8e7e-8cbad64846c8 ==============================
[0m02:16:39.132231 [info ] [MainThread]: Running with dbt=1.5.7
[0m02:16:39.133760 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/atef/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m02:16:39.134385 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/atef/project/E-Commerce-Order-Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:16:39.135339 [debug] [MainThread]: Command `dbt run` failed at 02:16:39.135196 after 0.13 seconds
[0m02:16:39.135844 [debug] [MainThread]: Flushing usage events
